[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  headers = {Cache-Control = "public, max-age=31536000, immutable"}

[functions]
  directory = ".netlify/functions"
