[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Essential for Next.js routing on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle Next.js static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[functions]
  directory = ".netlify/functions"
